name: motivation
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.5
  provider: ^6.0.3
  go_router: ^5.0.5
  pin_code_fields: ^7.4.0
  google_fonts: ^3.0.1
  hive_flutter: ^1.1.0
  hive:
  json_serializable: ^6.5.3
  logger: ^1.1.0
  # flutter_secure_storage: ^6.0.0
  flutter_bloc: ^8.1.1
  audioplayers: ^1.1.1
  # dio: ^4.0.6
  formz: ^0.4.1
  image_picker: ^0.8.6
  equatable: ^2.0.5
  flutter_quill: ^6.1.7
  flutter_quill_extensions: ^0.1.0
  chip_list: ^2.3.3+8
  photo_manager: ^2.5.2
  # isar: ^3.0.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator:
  build_runner:
  

flutter:

  uses-material-design: true
  assets:
    - assets/icons/icons_dark_theme/
    - assets/icons/icons_light_theme/
    - assets/icons/unactive_icons_dark_theme/
    - assets/icons/unactive_icons_light_theme/
    - assets/audio/sentmessage.mp3

  fonts:
    - family: YandexSansText
      fonts:
        - asset: assets/fonts/YandexSansText-Bold.ttf
          weight: 900
        - asset: assets/fonts/YandexSansText-Medium.ttf
          weight: 700
        - asset: assets/fonts/YandexSansText-Regular.ttf
          weight: 500
        - asset: assets/fonts/YandexSansText-Light.ttf
          weight: 300
        - asset: assets/fonts/YandexSansText-Thin.ttf
          weight: 100
